version: '3.3'

services:
  backend:
    image: my-node-app
    container_name: my-node-container
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL="mongodb://santynitin7:BCFpmwt2FCwds9wb@cluster0.ueffmqc.mongodb.net/prisma-2?retryWrites=true&w=majority&appName=Cluster0"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
