# Use the latest LTS version of Node.js
FROM node:lts-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Run Prisma generate to generate Prisma Client
RUN prisma generate

# Expose the port on which your Node.js application will run
EXPOSE 4000

# Command to run the Node.js application
CMD ["npm", "start"]
